# Generated by Django 6.0 on 2025-12-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_planets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('pl_rade', models.FloatField(blank=True, help_text='Planet radius (Earth radii)', null=True)),
                ('pl_masse', models.FloatField(blank=True, help_text='Planet mass (Earth masses)', null=True)),
                ('pl_eqt', models.FloatField(blank=True, help_text='Equilibrium temperature (K)', null=True)),
                ('pl_insol', models.FloatField(blank=True, help_text='Insolation flux (Earth flux)', null=True)),
                ('pl_orbper', models.FloatField(blank=True, help_text='Orbital period (days)', null=True)),
                ('pl_orbsmax', models.FloatField(blank=True, help_text='Semi-major axis (AU)', null=True)),
                ('pl_orbeccen', models.FloatField(blank=True, help_text='Orbital eccentricity', null=True)),
                ('st_teff', models.FloatField(blank=True, help_text='Stellar temperature (K)', null=True)),
                ('st_rad', models.FloatField(blank=True, help_text='Stellar radius (Solar radii)', null=True)),
                ('st_mass', models.FloatField(blank=True, help_text='Stellar mass (Solar masses)', null=True)),
                ('st_lum', models.FloatField(blank=True, help_text='Stellar luminosity', null=True)),
                ('st_logg', models.FloatField(blank=True, help_text='Stellar surface gravity', null=True)),
                ('st_met', models.FloatField(blank=True, help_text='Stellar metallicity', null=True)),
                ('st_age', models.FloatField(blank=True, help_text='Stellar age (Gyr)', null=True)),
                ('stellar_type', models.CharField(blank=True, help_text='Stellar spectral type', max_length=10)),
                ('habitability_class', models.CharField(choices=[('NON_HABITABLE', 'Non-Habitable'), ('HABITABILITY_ZONE', 'Habitability Zone'), ('POTENTIALLY_HABITABLE', 'Potentially Habitable')], db_index=True, default='NON_HABITABLE', max_length=50)),
                ('in_habitable_zone', models.BooleanField(db_index=True, default=False)),
                ('potentially_habitable', models.BooleanField(db_index=True, default=False)),
                ('esi_overall', models.FloatField(blank=True, help_text='Overall ESI score', null=True)),
                ('discovery_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='planets.mission')),
            ],
            options={
                'db_table': 'exoplanets',
                'ordering': ['planet_name'],
                'indexes': [models.Index(fields=['mission', 'habitability_class'], name='exoplanets_mission_e537af_idx'), models.Index(fields=['potentially_habitable'], name='exoplanets_potenti_caf980_idx'), models.Index(fields=['planet_name'], name='exoplanets_planet__70dd31_idx')],
            },
        ),
    ]
