# Generated by Django 6.0 on 2026-09-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exoplanet",
            name="disposition",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Raw archive disposition (CONFIRMED, CANDIDATE, PC, CP, KP, APC)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exoplanet",
            name="is_confirmed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for CONFIRMED / CP / KP; False for candidate-class objects",
            ),
        ),
        migrations.AddIndex(
            model_name="exoplanet",
            index=models.Index(
                fields=["is_confirmed", "habitability_class"],
                name="exoplanets_is_conf_592483_idx",
            ),
        ),
    ]
